server:
  port: 12346
  servlet:
    context-path: /app

spring:
  application:
    name: common

# eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#      fetchRegistry: false