server:
  port: 8166
  servlet:
    context-path: /web-market-carts
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  recomendations-service:
    url: http://localhost:5555/recommendations
  core-service:
    url: http://localhost:5555/core